FROM golang:1.21-alpine AS build
WORKDIR /src
COPY . .
RUN apk add --no-cache git
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /downstream ./cmd/downstream

FROM scratch
COPY --from=build /downstream /downstream
EXPOSE 8081
ENTRYPOINT ["/downstream"]
